version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: echo 'export MONGODB_URI="FOO"' >> $MONGODB_URI
      - run:
          command: echo 'export PORT="FOO"' >> $PORT
      - run:
          command: npm start
      - run:
          command: npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test